train: ../data/train/images
#val: ../data/valid/images

nc: 7  # Количество классов (0-6)
names: ['unclear_defect', 'scratch', 'dead_pixel', 'keyboard_problem', 'lock_issue', 'missing_screw', 'chip']
